name: Deploy to GitHub Pages

# Triggers: push to main + manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify web directory exists
        run: |
          if [ ! -d "web" ]; then
            echo "Error: web directory not found"
            exit 1
          fi
          if [ -z "$(ls -A web)" ]; then
            echo "Error: web directory is empty"
            exit 1
          fi

      - name: Prepare deployment directory
        run: |
          mkdir -p dist
          cp -r web/. dist/
          # Replace model.onnx.data with jsDelivr URL
          find dist -name "*.html" -type f -exec sed -i 's#model\.onnx\.data#https://cdn.jsdelivr.net/gh/cziter15/watermark-removal-webgpu@main/web/model.onnx.data#g' {} +
          # Replace model.onnx with jsDelivr URL
          find dist -name "*.html" -type f -exec sed -i 's#model\.onnx#https://cdn.jsdelivr.net/gh/cziter15/watermark-removal-webgpu@main/web/model.onnx#g' {} +

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
